name: ds_game
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.2
  google_fonts: ^4.0.3
  flutter_screenutil: ^5.6.1
  flutter_svg: ^1.1.0
  pinput: ^2.2.10
  firebase_auth: ^4.2.6
  firebase_core: ^2.5.0
  google_sign_in: ^5.4.4
  flutter_facebook_auth: ^5.0.7
  lottie: ^2.2.0
  shared_preferences: ^2.0.17
  fade_and_translate: ^0.1.3
  network_info_plus: ^3.0.2
  firebase_database: ^10.0.11
  provider: ^6.0.5
  cloud_functions: ^4.0.9
  pushable_button: ^0.0.3
  audioplayers: ^0.20.0
  delayed_display: ^2.0.0
  flip_card: ^0.7.0
  firebase_ui_database: ^1.0.16



























dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  flutter_launcher_icons: ^0.10.0



flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.jpg"


flutter:
  uses-material-design: true
  assets:
     - assets/images/
     - assets/lottie_images/
